language: elixir
git:
  depth: 1000
cache:
  directories:
  - _build
  - deps
services:
- docker
- redis-server
- rabbitmq
- postgresql
addons:
  postgresql: "9.6"
  apt:
    update: true
    packages:
    - docker-ce
elixir:
- 1.6.6
otp_release:
- 21.0.3
notifications:
  slack: kimlic:1fQoIvvw0ckjFF5Bgftxggmf
env:
  global:
  - Chart=kimlic-core
  - MIX_ENV=test
  - REQUIRE_VERSION_TAGS="true"
  - DOCKER_HUB_ACCOUNT=kimlictr
  - TRUNK_BRANCH="develop"
  - TRAVIS_REPO_SLUG="Kimlic/kimlic-elixir"
  - ENCRYPTION_LABEL="75f1c6481c4b"
  - secure: "KiUGSC6ZP2hEBd0Qx9gEh1AdQM36rnnYZmkCgjXoPPjjxjFrb2lNJ95sRAMGbrjX6DmeCcSmW46Kjd8MnNQDjVeOysOQCNyx8tZKUHUJYotZ6tLmebbxUDF6XW1Ux1tFkacY4gFW9F/xKnzSLvKJ6JCPX1iMNff9Afab4vUnlwpSxpliPeBX9/3Cbjg4KGjWw08YpN6FrarkCycvymS40dSDbjgBdEKmqBqlFI+M2jJYrR5oS/GNfvpBPFDBCkjoLLaHOVCLK7S82sKSGQCeAaA2Gu8QRvHsAcI9APqOIuwJhTq9y3y4KsoFbj7mvwzhva8l6zztSup3PZ3FGK5lsz8yCpIauwDWp3m0Xzs0n4DKrSpihPgIfutG2WqDHou02ynluqjlo3zmkA6DV3u+IkOcM1dVJqgGyO398dQjublMguzuGKA0w8nYLQH4Bvcr2Xg/osn3MJ7OZzSPhMIZ1SidG7PCxU5rELivvby8rkV4EDNySPq4JSd9who2VptUA4RXIzGNu56PaEmcPv0SKIfII9qLLREy1oV13lMc6ctYszUbztAq57KM02GTkd82wqEOBLv338XfG+80JP5x06EJPpXrA4sPjKlX0Wwq0YDdyZsN02YavtHgzOx0k1zZ+MGHyFZSzv2CuKgz5YCNyUBMs3smT6YyCDg997qFMXg="
  - secure: "vSFzJFrPS2TBAIoSB1hyaiUtJJ5tM9VHuh4jxeF4GkT9UOwSuWFzipInmHZdQKRb/VazJKr4R8dvCj6MHEA5tjTbKXk63Pjhq5DaN2BCafx6HRvrGtn9e/7gcDDntpYlkQiBmXkvBsyn9KoMj08tXOThtEcaG089C9NoxUYoad+kzN2C6RYvnbjSZ5qP+C24ilheTT+j9B1jxE/Gcp1RXU+K1mmmZX+ddMrQx4ka4+4gaPAfXT/X9iT+cqwKQJ2psu2GDilY/j89KUbDtCFZR4Q/9zwTIQ7dU9MFLcw1OMEmBAmJjOiKIOGCb/TxJMKcRh9JILeRb3PI2FakfAiLR3imHSzsP4LCqvRT8J1Vs4edtw4l5d0TPCNAn9UrZG+rblQBckgThu6lJxDB0jBYYBzyAa76mYIBBcz5aKZiKG7wNLjZ7PUsSAEvq4DxqaxEq1kZHYe9OMHG1DrrtbkkC/J9Y1ixcSurcDuZZlIA3+wJp43cHoUAyypAAV8tIUvtieAcHsoMQUmq6Fi1jbgveWWiLXlCroaDYr7DIzO8Mh3h4JV1KJf7YtrmvLip4PCJZDq8g8RJuFQdzKUpHl4DLBVu0AnHh7PzVOq973MiZ5AlnZjvZZ2K6+K/504bSjR80kM++4aC5DTa+7k4Wbfkn0u13GBCjIY4532iYAev1ro="
branches:
  except:
  - "/[0-9]*\\.[0-9]*\\.[0-9]*/"
before_install:
# Expose RabbitMQ to Docker container
- sudo ./bin/ci/init-rabbitmq.sh
# Expose Postgres
- sudo ./bin/ci/init-db.sh
jobs:
  include:
    - stage: "Test and build"
      name: "Run tests and build Docker container for mobile_api"
      env:
        - APPLICATION_PATH="apps/mobile_api"
      script:
        - source ./bin/ci/release/fetch-project-environment.sh
        - source ./bin/ci/release/fetch-source-version.sh
        - ./bin/mix_tests.sh || travis_terminate 1
        - ./bin/ci/release/put-source-version.sh || travis_terminate 1
        - ./bin/ci/release/build-container.sh || travis_terminate 1
        - sudo ./bin/ci/release/start-container.sh
        - sudo ./bin/ci/release/check-container.sh || travis_terminate 1
        - ./bin/ci/release/push-container.sh || travis_terminate 1
        - ./bin/ci/release/push-version.sh || travis_terminate 1

    - stage: "Test and build"
      name: "Run tests and build Docker container for attestation_api"
      env:
        - APPLICATION_PATH="apps/attestation_api"
      script:
      - source ./bin/ci/release/fetch-project-environment.sh
      - source ./bin/ci/release/fetch-source-version.sh
      - ./bin/mix_tests.sh || travis_terminate 1
      - ./bin/ci/release/put-source-version.sh || travis_terminate 1
      - ./bin/ci/release/build-container.sh || travis_terminate 1
      - sudo ./bin/ci/release/start-container.sh
      - sudo ./bin/ci/release/check-container.sh || travis_terminate 1
      - ./bin/ci/release/push-container.sh || travis_terminate 1
      - ./bin/ci/release/push-version.sh || travis_terminate 1